### PR TITLE
Fix cases for font-face styles

### PR DESCRIPTION
**Pull request by angus-c**

### CODE REVIEW

**Comment by derekjuber** [comment]
What happened with the lock file that stripped the integrity fields?

**Comment by angus-c** [comment]
> What happened with the lock file that stripped the integrity fields?

I don't know. This seems to happen randomly. Do you know what purpose the integrity fields serve?

**Comment by chrisdothtml** [comment]
See yarnpkg/yarn#6440 for info about the integrity lines

**Comment by angus-c** [comment]
> See yarnpkg/yarn#6440 for info about the integrity lines

Much clearer now 😱

**Pull request merged**
